#pragma once

namespace Silent
{
    extern float g_FullscreenAlphaBlend;

    /** @brief Enum containing the index of each filename.
     *
     * @note The .inc file is generated by `silentassets`.
     */
    enum e_FsFile
    {
        #include "Game/FileEnum.h.inc"
    };
 
    void Entry();
}
