#include "Framework.h"
#include "Engine/Services/String.h"

namespace Silent::Services
{
    constexpr auto FONT_8_GLYPH_PIXEL_SIZE  = Vector2i(8, 8);
    constexpr auto FONT_16_GLYPH_PIXEL_SIZE = Vector2i(12, 16);

    static const std::unordered_map<char, Vector2i> FONT_8_GLYPH_COORDS // Key = `char`, value = coordinate in `TIM/FONT8.TIM` 8x8 glyph atlas.
    {
        { '*', Vector2i(1, 0) },
        { '+', Vector2i(2, 0) },
        { ',', Vector2i(3, 0) },
        { '-', Vector2i(4, 0) },
        { '.', Vector2i(5, 0) },
        { '/', Vector2i(6, 0) },
        { '0', Vector2i(7, 0) },
        { '1', Vector2i(8, 0) },
        { '2', Vector2i(9, 0) },
        { '3', Vector2i(10, 0) },
        { '4', Vector2i(11, 0) },
        { '5', Vector2i(12, 0) },
        { '6', Vector2i(13, 0) },
        { '7', Vector2i(14, 0) },
        { '8', Vector2i(15, 0) },
        { '9', Vector2i(16, 0) },
        { ':', Vector2i(17, 0) },
        { ';', Vector2i(18, 0) },
        { '<', Vector2i(19, 0) },
        { '=', Vector2i(20, 0) },
        { '>', Vector2i(21, 0) },
        { '?', Vector2i(22, 0) },
        { '@', Vector2i(23, 0) }, // "©".
        { 'A', Vector2i(24, 0) },
        { 'B', Vector2i(25, 0) },
        { 'C', Vector2i(26, 0) },
        { 'D', Vector2i(27, 0) },
        { 'E', Vector2i(28, 0) },
        { 'F', Vector2i(29, 0) },
        { 'G', Vector2i(30, 0) },
        { 'H', Vector2i(31, 0) },
        { 'I', Vector2i(32, 0) },
        { 'J', Vector2i(0, 1) },
        { 'K', Vector2i(1, 1) },
        { 'L', Vector2i(2, 1) },
        { 'M', Vector2i(3, 1) },
        { 'N', Vector2i(4, 1) },
        { 'O', Vector2i(5, 1) },
        { 'P', Vector2i(6, 1) },
        { 'Q', Vector2i(7, 1) },
        { 'R', Vector2i(8, 1) },
        { 'S', Vector2i(9, 1) },
        { 'T', Vector2i(10, 1) },
        { 'U', Vector2i(11, 1) },
        { 'V', Vector2i(12, 1) },
        { 'W', Vector2i(13, 1) },
        { 'X', Vector2i(14, 1) },
        { 'Y', Vector2i(15, 1) },
        { 'Z', Vector2i(16, 1) },
        { '^', Vector2i(17, 1) },
        { '_', Vector2i(18, 1) }
    };

    // TODO: Coords.
    static const std::unordered_map<char, Vector2i> FONT_16_GLYPH_COORDS // Key = `char`, value = coordinate in `1ST/FONT16.TIM` 12x16 glyph atlas.
    {
        { '\'', Vector2i() },
        { '(',  Vector2i() },
        { ')',  Vector2i() },
        { '*',  Vector2i() }, // "=".
        { '+',  Vector2i() },
        { ',',  Vector2i() },
        { '-',  Vector2i() },
        { '.',  Vector2i() },
        { '/',  Vector2i() },
        { '0',  Vector2i() },
        { '1',  Vector2i() },
        { '2',  Vector2i() },
        { '3',  Vector2i() },
        { '4',  Vector2i() },
        { '5',  Vector2i() },
        { '6',  Vector2i() },
        { '7',  Vector2i() },
        { '8',  Vector2i() },
        { '9',  Vector2i() },
        { ':',  Vector2i() },
        { ';',  Vector2i() },
        { '<',  Vector2i() },
        { '=',  Vector2i() }, // "-".
        { '>',  Vector2i() },
        { '?',  Vector2i() },
        { '@',  Vector2i() }, // Star.
        { 'A',  Vector2i() },
        { 'B',  Vector2i() },
        { 'C',  Vector2i() },
        { 'D',  Vector2i() },
        { 'E',  Vector2i() },
        { 'F',  Vector2i() },
        { 'G',  Vector2i() },
        { 'H',  Vector2i() },
        { 'I',  Vector2i() },
        { 'J',  Vector2i() },
        { 'K',  Vector2i() },
        { 'L',  Vector2i() },
        { 'M',  Vector2i() },
        { 'N',  Vector2i() },
        { 'O',  Vector2i() },
        { 'P',  Vector2i() },
        { 'Q',  Vector2i() },
        { 'R',  Vector2i() },
        { 'S',  Vector2i() },
        { 'T',  Vector2i() },
        { 'U',  Vector2i() },
        { 'V',  Vector2i() },
        { 'W',  Vector2i() },
        { 'X',  Vector2i() },
        { 'Y',  Vector2i() },
        { 'Z',  Vector2i() },
        { '[',  Vector2i() }, // Left double-quote.
        { '\\', Vector2i() }, // "!".
        { ']',  Vector2i() }, // Right double-quote.
        { '^',  Vector2i() }, // "&".
        { '_',  Vector2i() }, // Space.
        { '`',  Vector2i() },
        { 'a',  Vector2i() },
        { 'b',  Vector2i() },
        { 'c',  Vector2i() },
        { 'd',  Vector2i() },
        { 'e',  Vector2i() },
        { 'f',  Vector2i() },
        { 'g',  Vector2i() },
        { 'h',  Vector2i() },
        { 'i',  Vector2i() },
        { 'j',  Vector2i() },
        { 'k',  Vector2i() },
        { 'l',  Vector2i() },
        { 'm',  Vector2i() },
        { 'n',  Vector2i() },
        { 'o',  Vector2i() },
        { 'p',  Vector2i() },
        { 'q',  Vector2i() },
        { 'r',  Vector2i() },
        { 's',  Vector2i() },
        { 't',  Vector2i() },
        { 'u',  Vector2i() },
        { 'v',  Vector2i() },
        { 'w',  Vector2i() },
        { 'x',  Vector2i() },
        { 'y',  Vector2i() },
        { 'z',  Vector2i() }
    };

    static const std::unordered_map<char, int> FONT_16_GLYPH_PIXEL_WIDTHS
    {
        { '\'', 3 },
        { '(',  7 },
        { ')',  7 },
        { '*',  11 }, // "=".
        { '+',  11 },
        { ',',  4 },
        { '-',  10 },
        { '.',  4 },
        { '/',  6 },
        { '0',  10 },
        { '1',  10 },
        { '2',  10 },
        { '3',  10 },
        { '4',  10 },
        { '5',  10 },
        { '6',  10 },
        { '7',  10 },
        { '8',  10 },
        { '9',  10 },
        { ':',  4 },
        { ';',  4 },
        { '<',  10 },
        { '=',  11 }, // "-".
        { '>',  10 },
        { '?',  8 },
        { '@',  13 }, // Star.
        { 'A',  12 },
        { 'B',  12 },
        { 'C',  12 },
        { 'D',  13 },
        { 'E',  11 },
        { 'F',  11 },
        { 'G',  13 },
        { 'H',  12 },
        { 'I',  9 },
        { 'J',  9 },
        { 'K',  12 },
        { 'L',  12 },
        { 'M',  13 },
        { 'N',  12 },
        { 'O',  13 },
        { 'P',  11 },
        { 'Q',  13 },
        { 'R',  12 },
        { 'S',  10 },
        { 'T',  11 },
        { 'U',  13 },
        { 'V',  12 },
        { 'W',  12 },
        { 'X',  12 },
        { 'Y',  11 },
        { 'Z',  12 },
        { '[',  6 },  // Left double-quote.
        { '\\', 4 },  // "!".
        { ']',  6 },  // Right double-quote.
        { '^',  8 },  // "&".
        { '_',  0 },  // Space.
        { '`',  3 },
        { 'a',  9 },
        { 'b',  10 },
        { 'c',  9 },
        { 'd',  9 },
        { 'e',  9 },
        { 'f',  7 },
        { 'g',  11 },
        { 'h',  11 },
        { 'i',  6 },
        { 'j',  6 },
        { 'k',  10 },
        { 'l',  6 },
        { 'm',  13 },
        { 'n',  11 },
        { 'o',  10 },
        { 'p',  11 },
        { 'q',  10 },
        { 'r',  8 },
        { 's',  8 },
        { 't',  7 },
        { 'u',  10 },
        { 'v',  10 },
        { 'w',  12 },
        { 'x',  10 },
        { 'y',  10 },
        { 'z',  9 }
    }; 
}
