#pragma once

namespace Silent
{
    /** @brief Enum containing index of each filename, for use with FS functions.
     *
     * @note The .inc file is generated by `silentassets`.
     */
    enum e_FsFile
    {
        #include "Engine/Game/fileenum.h.inc"
    };
 
    void Entry();
}
